### ISSUE TITLE
Error while Player.destroy(message.guild?.id);

### ISSUE THREAD

**Issue by RoMeAh-zz** [Projects-Me/LavaJS#1]
Promise { <pending> }
(node:19930) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at Player.destroy (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/Player.js:283:7)
    at /home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:54:34
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:19930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:19930) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at Player.destroy (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/Player.js:283:7)
    at Join.<anonymous> (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:60:28)
    at Generator.next (<anonymous>)
    at /home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:4:12)
    at Timeout._onTimeout (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:58:34)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:19930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Lavalink Server 2333: LavaJS] => Connected

**Comment by ThatAnonyG** [comment]
@IamGoDsoIamBest Thanks for letting us know. This error has been fixed in v2.0.3-patch. Upgrade to the same as soon as possible.
