### ISSUE TITLE
Error in this.lava.spawnPlayer()

### ISSUE THREAD

**Issue by RoMeAh-zz** [Projects-Me/LavaJS#2]
(node:17280) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'catch' of undefined
    at LavaClient.wsSend (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/LavaClient.js:150:29)
    at new Player (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/Player.js:70:17)
    at LavaClient.spawnPlayer (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/LavaClient.js:188:12)
    at Join.<anonymous> (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:34:84)
    at Generator.next (<anonymous>)
    at /home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:4:12)
    at Join.exec (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:31:16)
    at CommandHandler.runCommand (/home/romeah/Desktop/blazify-discord-bot/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:755:39)
(node:17280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ThatAnonyG** [comment]
@IamGoDsoIamBest Thanks for letting us know. This error has been fixed in v2.0.3-patch. Upgrade to the same as soon as possible.
