### ISSUE TITLE
It's not working with shards

### ISSUE THREAD

**Issue by emirkabal** [Projects-Me/LavaJS#21]
```
    Error: TypeError: Cannot read property 'send' of undefined
at LavaClient.wsSend (C:\Users\****\Desktop\*****\node_modules\@anonymousg\lavajs\dist\managers\LavaClient.js:127:41)
at new Player (C:\Users\***\Desktop\****\node_modules\@anonymousg\lavajs\dist\managers\Player.js:42:21)
at LavaClient.spawnPlayer (C:\Users\****\Desktop\****new\node_modules\@anonymousg\lavajs\dist\managers\LavaClient.js:158:16)
at Command.listener (C:\Users\***\Desktop\****\src\commands\music\oynat.js:19:37)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at runNextTicks (internal/process/task_queues.js:62:3)
at processImmediate (internal/timers.js:412:9)
```

**Comment by ThatAnonyG** [comment]
PR #20 fixes that error. I will release it today. Sorry for the delay.
