### ISSUE TITLE
Error in Player.lavaSearch()

### ISSUE THREAD

**Issue by RoMeAh-zz** [Projects-Me/LavaJS#3]
(node:18167) UnhandledPromiseRejectionWarning: TypeError: fetch(...).json is not a function
    at /home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/Player.js:134:10
    at new Promise (<anonymous>)
    at Player.lavaSearch (/home/romeah/Desktop/blazify-discord-bot/node_modules/@anonymousg/lavajs/dist/managers/Player.js:123:12)
    at Join.<anonymous> (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:51:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/romeah/Desktop/blazify-discord-bot/Blazify/Bot/Commands/Music/Join.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:18167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ThatAnonyG** [comment]
@IamGoDsoIamBest Thanks for letting us know. This error has been fixed in v2.0.3-patch. Upgrade to the same as soon as possible.
