### ISSUE TITLE
Player.play() not working

### ISSUE THREAD

**Issue by RoMeAh-zz** [Projects-Me/LavaJS#5]
First of all i spawn a player by one of my sub command ... After that i create a Player Instance its logging song properly but not actually playing it...

```ts
if(song === "join") {
            await this.client.lava?.spawnPlayer ( this.client.lava , {
        guild: message.guild?.id ,
        voiceChannel: message.member.voice.channel ,
        textChannel: message.channel ,
        deafen: true ,
        trackRepeat: false ,
        queueRepeat: false ,
        skipOnError: true
    } );
    message.util?.send(new MessageEmbed()
        .setAuthor("*Joined Voice Channel and I am ready..*")
        .setColor("GREEN")
        .setDescription(`\n
            \`Text Channel\`: ${message.channel}\n
            \`Voice Channel\`: ${message.member?.voice.channel}\n
            \`Guild Name\`: ${message.guild?.name}`)
    );
        } else {
            let player = new Player(this.client.lava, {
            guild: message.guild?.id ,
            voiceChannel: message.member.voice.channel ,
            textChannel: message.channel ,
            deafen: true ,
            trackRepeat: false ,
            queueRepeat: false ,
            skipOnError: true
        }, this.client.lava.optimisedNode)

        let queue = new Queue(player)
            let Song: any = await player.lavaSearch(song, message.member, true)
        if(!Song) return message.util?.send("No Song Found. Please Try Again")
            await player.play ();
            if(player.playState) {
            message.util?.send(new MessageEmbed()
                .setAuthor(Song.author)
                .setDescription(Song.title + `[${Song.title}](${Song.uri})`)
                .setImage(Song.thumbnail.max)
                .setThumbnail(`message.guild?.iconURL ( {dynamic: true} )`)
            )
                }
        console.log ( Song )
}```

**Comment by Johna-3212** [comment]
This issue is due to network latency, host both lavalink and bot on a vps and it will play music.

**Comment by RoMeAh-zz** [comment]
I tried erela, lavaclient and lavacord all of them are working so I don't think so that is a problem and yea no error is logged in lavalink console I'm hosting it in a vps

**Comment by Johna-3212** [comment]
Host your bot in a vps and try

**Comment by RoMeAh-zz** [comment]
Okay... I hosted my Bot and Lavalink on VPS and now i get this error 

```2020-06-15 03:11:01.904 ERROR 4590 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Exception while handling websocket message

org.json.JSONException: JSONObject["guildId"] not found.
        at org.json.JSONObject.get(JSONObject.java:573) ~[json-20190722.jar!/:na]
        at org.json.JSONObject.getString(JSONObject.java:836) ~[json-20190722.jar!/:na]
        at lavalink.server.io.WebSocketHandlers.play(WebSocketHandlers.kt:45) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessageSafe(SocketServer.kt:147) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:127) ~[classes!/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:113) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:84) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:286) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:604) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:594) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:266) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:317) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:182) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:951) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:932) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

```

**Comment by ThatAnonyG** [comment]
The docs clearly ask you to pass the guild object instead of ID. If you ever check our `LavaClient#spawnPlayer()` you will see that we resolve all the IDs into proper objects. 

And it's preferred to use the provided method `LavaClient#spawnPlayer()` instead of using the class unless you are extending it.
